def pods_networking
	pod 'Moya/Combine', '~> 15.0' #
end

def pods_log
	pod 'CocoaLumberjack/Swift', '~> 3.8' #
end


def pods_ui
	pod 'Toast-Swift', '~> 5.0' #
end

def pods_DI
	pod 'Swinject', '~> 2.8.0' #
end

def pods_Utils
	pod 'Then', '~> 3.0.0' #
end

def pods_Auth
	pod 'KakaoSDK'

	pod 'naveridlogin-sdk-ios' 
	pod 'GoogleSignIn'
end

def pods_Firebase
	pod 'Firebase/Analytics'
	pod 'Firebase/Crashlytics'
	pod 'FirebaseMessaging'
end


platform :ios, '15.0'

target 'Pet-ID-iOS' do
  use_frameworks!
	pods_DI
	pods_networking
	pods_log
	pods_ui
	pods_Utils
	pods_Auth
	pods_Firebase
end
