def pods_networking
	pod 'Moya/Combine', '~> 15.0' #
end

def pods_log
	pod 'CocoaLumberjack/Swift', '~> 3.8' #
end


def pods_ui
	pod 'Toast-Swift', '~> 5.0' #
end


platform :ios, '15.0'

target 'Pet-ID-iOS' do
  use_frameworks!
	pods_networking
	pods_log
	pods_ui
end
