# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'Pet-ID-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift'
  pod 'KakaoSDK'
 

  # Pods for Pet-ID-iOS

  target 'Pet-ID-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pet-ID-iOSUITests' do
    # Pods for testing
  end

end
